name: 博客更新
on:
  push:
    branch: dev

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@master

      - name: 安装依赖
        run: yarn

      - name: 构建
        run: yarn generate

      - name: 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master